### ISSUE TITLE
Correção do botão fechar nas mensagem de aletas

### ISSUE THREAD

**Issue by BrunoLagoa** [albasolucoes/busman#1]
Na view **layouts/admin.blade.php** na linha 58. Corrigir o código para esse abaixo.
Assim você corrige a posição do botão fechar, para posição correta.

```
.alert-dismissable .my-close,
.alert-dismissible .my-close {
  position: relative;
  top: -3px;
  right: -4px;
}
```

**Comment by marcelobdsilva** [comment]
Ajuste realizado. Obrigado!
